version: "3.7"

services:

  doc_classifier:
    build: ./app
    container_name: doc_classifier
    restart: always
    environment:
      - APP_NAME=DocClassifierApp
    expose:
      - 3000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "3000:3000"
