version: "2"

services:

  doc_classifier:
    build: .
    container_name: doc_classifier
    restart: always
    environment:
      - APP_NAME=DocClassifierApp
      - SUB_PATH=/
      - FLASK_CONFIG=work
    ports:
      - "3001:3001"