version: "3"

services:

  doc_classifier:
    build: ./app
    container_name: doc_classifier
    restart: always
    environment:
      - APP_NAME=DocClassifierApp
      - SUB_PATH=/prod/doc_classifier
    ports:
      - "3001:3001"
    volumes:
      - './app:/app'
