version: "3.7"

services:

  doc_classifier:
    build: ./app
    container_name: doc_classifier
    restart: always
    environment:
      - APP_NAME=DocClassifierApp
    ports:
      - "3000:3001"

